[package]
name = "edge_service"
version = "0.1.0"
authors = ["wolfgang friedl <wolfgang.friedl@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Easy Ctrl-C handler for Rust projects
ctrlc = "3.1.3"